### ISSUE TITLE
where do you enable rh-git29 ?

### ISSUE THREAD

**Issue by walidshaari** [sigio/ansible-role-vsts-agent#3]
Thank you for writing a role to document the requirements of the vsts-agent installation. one thing I have not found is where do you enable git29,  in my case I just started experimenting and running the run.sh interactively so I put it on run.sh. However, for production I think this needs to be covered.

**Comment by sigio** [comment]
Probably somewhere in the 'common' role that was used,,, this has only been used shortly and at 1 client.
